### ISSUE TITLE
[React-TypeScript] Cannot find module of dependent bit

### ISSUE THREAD

**Issue by FredyC** [teambit/bit.envs#49]
Rather strange error. I made a repo for easy reproduction: https://github.com/FredyC/bit-ts-react-test.

![error](https://user-images.githubusercontent.com/1096340/64106922-83f32e00-cd79-11e9-8986-f403553610c4.png)

@qballer Can you please have a look?

**Comment by qballer** [comment]
thanks for opening an issue @FredyC I will look in to that and get back here.

**Comment by GiladShoham** [comment]
@FredyC Hi,
There is a bug with react-typescript v3.0.16.
You should update to version 3.0.17 and it will work.

**Comment by qballer** [comment]
Yep, I published that version yesterday. It's very strange this wasn't picked up before.
It should be fixed. let me know if there is an issue.

**Comment by FredyC** [comment]
Awesome seems to be working, that was really lucky to report something that was already fixed :)

**Comment by qballer** [comment]
We do try. :)

**Comment by FredyC** [comment]
Well, it seems that something is still wonky even with 3.0.17. The same error appeared for a different component for some reason...

```
error: bit failed to build speedlo.hooks/use-route-params@0.2.0 with the following exception:
Command failed: D:\hooks\.bit\components\compilers\react-typescript\bit.envs\3.0.17\components\.dependencies\compilers\typescript\bit.envs\3.0.15\node_modules\typescript\bin\tsc -d

useRouteMatch.ts(1,31): error TS2307: Cannot find module '@bit/speedlo.hooks.use-route-match'.
```

The `bit status` has a weird output too... Why does it want to use scoped component instead of local one I wonder. What we did is that before the `useRouteParams` depended on `useRouterContext` directly. Now there is `useRouteMatch` between these two.

```
pending updates
(use "bit checkout [version] [component_id]" to merge changes)
(use "bit diff [component_id] [new_version]" to compare changes)
(use "bit log [component_id]" to list all available versions)

    > speedlo.hooks/use-route-params current: 0.2.0 latest: 0.2.1

modified components
(use "bit tag --all [version]" to lock a version with all your changes)
(use "bit diff" to compare changes)

     > use-route-match ... ok
     > use-route-params ... ok
```

I tried upgrading to the latest 3.0.21 and it fails for the same component, but more cryptic error. I assume it's a same thing, but error is swallowed somewhere now.

```
error: bit failed to build speedlo.hooks/use-route-params@0.2.0 with the following exception:
Command failed with exit code 2 (Unknown system error -2): D:\hooks\.bit\components\compilers\react-typescript\bit.envs\3.0.21\components\.dependencies\compilers\typescript\bit.envs\3.0.25\node_modules\typescript\bin\tsc -d
Error: Command failed with exit code 2 (Unknown system error -2): D:\hooks\.bit\components\compilers\react-typescript\bit.envs\3.0.21\components\.dependencies\compilers\typescript\bit.envs\3.0.25\node_mo
```

**Comment by qballer** [comment]
Hi @FredyC, This issue is with the main dist file of the component should be resolved in v3.0.22.

**Comment by FredyC** [comment]
@qballer Where did I said anything about main file? 😕There was different issue #43 which wasn't a problem since v17. Even with v22 the issue I've described in a previous comment still persist. I simply cannot get through tag & build and I don't know what went wrong and why.

![image](https://user-images.githubusercontent.com/1096340/64636336-c663dd00-d401-11e9-93c2-e068a5e27b40.png)

That line of code it mentions is not anywhere in source files so I really don't know what's going on :/

**Comment by qballer** [comment]
Lets sort this out on gitter
