### ISSUE TITLE
wrong distMainFile in ts compiler

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit.envs#57]
See full explain and re-produce here: https://github.com/teambit/bit/issues/1978

copy the description by @davidfirst  from the mentioned issue:

`bit.envs/compilers/typescript@3.0.22`. 
It randomly returns a wrong distMainFile. Sometimes `index.js`, sometimes `index.js.map`.

Looking at the compiler code, the issue is with this function:
```
export function findMainFile(context: CompilationContext, dists: Vinyl[]) {
    const getNameOfFile = (val:string, split:string) => val.split(split)[0]
    const sourceFileName = getNameOfFile(context.main, '.ts')
    const res = dists.find((val)=> {
        return  sourceFileName === getNameOfFile(val.basename, '.js')
    })
    return  (res || {relative:''}).relative
}
```
it splits the filename by '.js' and compare to the basename, so both names (index.js and index.js.map) fit the criteria.

**Comment by qballer** [comment]
Hey the root cause of the issue was wrong`mainDistFile`. I've fixed it in 3.0.26. I've also tested in the original project and the main file seems good.

**Comment by davidfirst** [comment]
This issue still persists.
@qballer , as you can see on Gitter, @DeyLak are still having issues due to the wrong main-file.
I also tried myself. I imported the lastest (3.0.29) version of the typescript compiler, added a console.log to check what mainFile I get, and I get the `.map.js` sometimes.

**Comment by davidfirst** [comment]
I fixed the component itself and tagged 3.0.30.
I didn't sync it with the repo. I leave this task open for @qballer  to take care of that and code review my changes.
